### PR TITLE
Add released types to scm

### PR DESCRIPTION
**Pull request by jbolinger**
Add the generated files to git, and remove `lib/` from `.gitignore`, in preparation for subsequent releases.

### CODE REVIEW

**Comment by blowmage** [comment]
These are the files used in the googleapis-common-protos 1.3.8 release and the googleapis-common-protos-types 1.0.3 release?

**Comment by jbolinger** [comment]
Yes, this should match the currently released gem.

**Comment by blowmage** [comment]
Should CI be calling compile_protos as part of the build or release? Wouldn’t that potentially replace the files in git with whatever is generated on CI?

**Comment by jbolinger** [comment]
The release is not automated vi CI so I don't think that's an issue for now. It's just a sanity check that runs the build, and since we're checking everything in now it makes the CI pretty useless as-is.

**Pull request merged**
